# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
