# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20161212_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='boughtPrice',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
