# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170107_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Users'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
